redis.host={{YOUR_REDIS_HOST}}
redis.port=6379
redis.password={{YOUR_REDIS_PASSWORD}}
mq.host={{YOUR_MQ_HOST}}
mq.port=5672
mq.username={{YOUR_MQ_USERNAME}}
mq.password={{YOUR_MQ_PASSWORD}}
mq.virtualHost={{YOUR_MQ_VHOST}}
